# Generated by Django 5.2.7 on 2025-11-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atricle',
            new_name='Article',
        ),
    ]
